version: '3'
services:
 
  validate:
    image: flyway/flyway
    command: -configFiles=/flyway/conf/flyway.config -connectRetries=60 validate
    volumes:
      - ${PWD}/sql:/flyway/sql
      - ${PWD}/docker-flyway.config:/flyway/conf/flyway.config
    depends_on:
      - postgres
      
  postgres:
    image: postgres:latest
    restart: always
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=myportalsecret
    - POSTGRES_DB=portdb
