name: PostgreSQL Migration Test with Flyway 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  run_migration_test:
    name: Migration tests
    runs-on: ubuntu-latest
    # [self-hosted, ubuntu-latest, x64] - this is for self hosted container
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Migrate Database 
        run: ./migration-test-prod.sh
        env:
          SPAWNCTL_ACCESS_TOKEN: ${{ secrets.SPAWNCTL_ACCESS_TOKEN }}
      - name: Clean-up Resources 
        run: ./destroy-db-dockers.sh
    
