name: PostgreSQL Migration Test with Flyway 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  run_migration_test:
    name: Migration tests
    runs-on: [self-hosted, ubuntu-latest, x64]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run database migrations against prod backup
        run: ./migration-test-prod.sh
        env:
          SPAWNCTL_ACCESS_TOKEN: ${{ secrets.SPAWNCTL_ACCESS_TOKEN }}
